# Generated by Django 4.2.16 on 2024-10-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(db_index=True, max_length=128)),
                ('reading_value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
