# Generated by Django 4.2.16 on 2024-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_hoodactuatorconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LampActuatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField()),
            ],
        ),
    ]
