# Generated by Django 4.2.16 on 2024-11-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_lampactuatorconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringActuatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField()),
            ],
        ),
    ]
