# Generated by Django 4.2.16 on 2024-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_wateringactuatorconfig_max_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('is_excess', models.BooleanField()),
                ('text', models.TextField()),
            ],
        ),
    ]
